### ISSUE TITLE
Automatic database initialization...

### ISSUE THREAD

**Issue by mgajda** [entangled/entangled#62] opened 2020-07-01 11:50 UTC
After defining the `entangled.dhall` file and trying to run `entangled tangle` with uninitialized database we see no output.
It would be nice to get automatic initialization of database, or warn user that it should be checked into the repository.

**Comment by jhidding** [comment] 2020-07-02 09:06
The database is not supposed to be checked into the repository. I recommend adding it to .gitignore

**Comment by jhidding** [comment] 2020-07-02 09:24
After rereading your issue, I think this is also a duplicate of issue #49. We should add a flag for automated `insert` on tangle and list commands.

**Closed by jhidding** 2020-07-02 09:24 UTC
