### ISSUE TITLE
Support language without comments

### ISSUE THREAD

**Issue by sverhoeven** [entangled/entangled#64] opened 2020-08-11 07:46 UTC
I have a JSON document in a Markdown file like so

~~~markdown
```{.json #request-schema}
{
  "key": "value"
}
```
~~~

I compose this into a yaml and JavaScript code block.

Running `entangled tangle -a` gives me a `UnknownLanguageClass "json"` error. 

JSON does not support comments and yaml uses `#` for comment and JavaScript uses `//` for comment.
I tried to add JSON language to the config file, but was unable to define a suitable comment style. 
Please advise how to approach this problem.

**Comment by sverhoeven** [comment] 2020-08-11 08:09
For reference I am having this problem in https://github.com/NLESC-JCER/cpp2wasm/tree/45-entangled

**Comment by justjosias** [comment] 2020-08-11 11:54
Duplicate of #27

**Comment by mgajda** [comment] 2020-10-19 14:00
A more careful look indicates that there is unofficial standard of adding [`"_comment"` key](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json) to the object, but this cannot be placed arbitrarily in the input.

**Comment by jhidding** [comment] 2021-07-17 16:44
Indeed duplicate of #27

**Closed by jhidding** 2021-07-17 16:44 UTC
