### ISSUE TITLE
Haddock comments in literate source

### ISSUE THREAD

**Issue by mgajda** [entangled/entangled#86] opened 2021-02-11 10:00 UTC
It is important to have a proper reference in `haddock` format so that we can see description of each function, datatype and module.

Other languages have similar documentation formats: javadoc, pydoc etc.

They are easily accessed in IDE when editing code, and serve as library documentation.

It would probably suffice to include last paragraph or a block before each function as documentation, instead of ignoring it when generating the code. Would it?

**Comment by jhidding** [comment] 2021-02-12 15:04
Hi Michał,
That is a nice idea that also crossed my mind. There are several problems with this though:

1. Haddock documentation and literate sources are different types of documentation. Literate source gives an overview of the architecture as well as explaining the inner workings of a code, while Haddock is meant purely for API documentation. I developed Entangled for use with scientific codes in mind. Scientific codes have the unique property that a user is automatically also interested in the workings of the method. API documentation is for developers using the outer skin of a library.

2. Your suggestion is far from trivial to implement. It is far easier to filter out Haddock comments when presenting the generated document (or make them collapsible elements). This would have to be implemented in entangled/filters (in fact there is an issue: entangled/filters#8).
3. Maybe a matter of taste: I don't like implicit behaviours. Including a "previous paragraph" may be nice for many cases, but is very hard to control in a general setting.

Concluding: API documentation and literate presentation should contain different information for different target audiences: ideally you should write both and present one or the other, possibly cross-linked. I would welcome contributions to entangled/filters to this end.

**Comment by jhidding** [comment] 2021-07-17 16:02
Duplicate of #61

**Closed by jhidding** 2021-07-17 16:02 UTC
